const CREDENTIALS =
  {
    "AWS_COGNITO_USER_POOL_ID": "us-east-2_ZZE2LX6Km",
    "AWS_COGNITO_CLIENT_ID": "1srrvcqp4kucu0gv0bfuok3l72",
    "AWS_COGNITO_REGION": "us-east-2",
    "AWS_COGNITO_IDENTITY_POOL_ID":"AWS_COGNITO_IDENTITY_POOL_ID"
  }
module.exports = CREDENTIALS;
